import { Inter } from 'next/font/google';
import './globals.css';
import '@/assets/css/bootstrap.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/assets/css/line-awesome.min.css';
import '@/assets/css/style.css';

// import "@ass"

export const metadata = {
  title: 'Pets Golden',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='expand-menu'>{children}</body>
    </html>
  );
}
